# Generated by Django 3.1 on 2020-11-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex_home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='iosUserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('phone', models.CharField(max_length=12)),
                ('wpnumber', models.CharField(max_length=12)),
                ('budget', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=250)),
                ('applications', models.CharField(max_length=150)),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MobUserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.CharField(max_length=12)),
                ('wpnumber', models.CharField(max_length=12)),
                ('budget', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=250)),
                ('applications', models.CharField(max_length=150)),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebUserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('phone', models.CharField(max_length=12)),
                ('wpnumber', models.CharField(max_length=12)),
                ('budget', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=250)),
                ('applications', models.CharField(max_length=150)),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='winUserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('phone', models.CharField(max_length=12)),
                ('wpnumber', models.CharField(max_length=12)),
                ('budget', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=250)),
                ('applications', models.CharField(max_length=150)),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
        ),


        migrations.CreateModel(
            name='ContactUserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.CharField(max_length=12)),
                ('wpnumber', models.CharField(max_length=12)),
                ('budget', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=250)),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
        ),


        migrations.DeleteModel(
            name='services',
        ),
    ]
